services:
  - type: web
    name: flask template
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: gunicorn -w 4 -b 0.0.0.0:8000 wsgi:app
    staticPublishPath: static/uploads